.PHONY: tsshop-api

dev:
		./docker_iter.sh tsshop-api 9073:9073 dev 9075:9075
prod:
		./docker_iter.sh tsshop-api 9073:9073 prod 9075:9075
test:
		./docker_iter.sh tsshop-api 9073:9073 test 9075:9075
